# Generated by Django 4.1.2 on 2023-03-26 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('current_energy_rating', models.CharField(max_length=100)),
                ('potential_energy_rating', models.CharField(max_length=100)),
                ('current_energy_efficiency', models.CharField(max_length=100)),
                ('potential_energy_efficiency', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('co2_emissions_current', models.CharField(max_length=100)),
                ('co2_emissions_potential', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
