# Generated by Django 4.1.2 on 2023-03-26 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPCRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_energy_rating', models.CharField(max_length=100)),
                ('potential_energy_rating', models.CharField(max_length=100)),
                ('current_energy_efficiency', models.CharField(max_length=100)),
                ('potential_energy_efficiency', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('co2_emissions_current', models.CharField(max_length=100)),
                ('co2_emissions_potential', models.CharField(max_length=100)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epc_ratings', to='house.house')),
            ],
        ),
    ]
